[package]
name = "tango-virus"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0"
clap = { version = "3.0", features = ["derive"] }
csv = "1.1"
itertools = "0.10"
ordered-float = "2.10"
string-interner = "0.14"
newick-rs = "0.2"
thiserror = "1.0"
