[package]
name = "meteor"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0"
clap = { version = "3.0", features = ["derive"] }
crossbeam = "0.8"
csv = "1.1"
extended-rational = "1.3"
itertools = "0.10"
newick-rs = "0.2"
ordered-float = "2.10"
polars = { version = "0.20", features = ["lazy", "list", "decompress"] }
polars-io = "0.20"
polars-lazy = "0.20"
rayon = "1.5"
regex = "1.5"
serde = "1.0"
serde_cbor = "0.11"
serde_json = "1.0"
serde_with = "1.12"
string-interner = { version = "0.14", features = ["serde"] }
thiserror = "1.0"
